# Generated by Django 2.2.14 on 2021-05-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField(default=5.0)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product/iamges/')),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
    ]
